---
- name: Listen for alert notifications from Splunk
  hosts: localhost
  ## Listening on port 5000.
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
      ## Checking for Organization modification Alert
    - name: AAP Organization Modified
      condition: event.payload.app == 'ansible_addon_for_splunk' and event.payload.results.message == 'Activity Stream update entry for organization'
      # Modify the RBAC role for the organization
      action:
        debug:
          msg:
            - "operation is :{{ event.payload.results['operation'] }}"
            - "or namew is  :{{ event.payload.results['changes.name'] }}"
            - "or id is  :{{ event.payload.results['changes.id'] }}"
        # run_job_template:
        #   name: EDADemo-action-splunk-modify-team-role
        #   organization: "{{ job_templates_org_name | default('Foxhound') }}"
        #   job_args:
        #     extra_vars:
        #       org_operation: "{{ event.payload.results['operation'] }}"
        #       org_name: "{{ event.payload.results['changes.id'] }}"
        #       org_id: "{{ event.payload.results.['changes.name'] }}"
