---
- name: Modify the team role in AAP to include all organization permissions
  hosts: all
  gather_facts: false
  tasks:
    - name: Give Global Support Team Org Audit and Org Execute on all organizations
      ansible.controller.role_team_assignment:
        role_definition: "{{ item }}"
        object_id: 65
        team: "{{ input_team_name | default('global-support') }}"
        state: "{{ 'present' when org_operation == 'create' else 'absent' }}"
      loop:
      - Organization Execute
      - Organization Audit

	

